version: "3"
services:
  squid-proxy:
    image: sameersbn/squid:latest
    ports:
      - "3128:3128"
    volumes:
     - squid-cache:/var/spool/squid
    restart: unless-stopped
volumes:
  squid-cache:
