#!/bin/bash
set -e

if [ -f /etc/squid3/squid.user.conf ]; then
  cp /etc/squid3/squid.user.conf /etc/squid3/squid.conf
fi

# fix permissions on the log dir
sudo -u proxy -H mkdir -p /var/log/squid3
chmod -R 755 /var/log/squid3
chown -R proxy:proxy /var/log/squid3

# fix permissions on the cache dir
sudo -u proxy -H mkdir -p /var/spool/squid3
chown -R proxy:proxy /var/spool/squid3

# initialize the cache_dir
if [ ! -d /var/spool/squid3/00 ]; then
  /usr/sbin/squid3 -N -f /etc/squid3/squid.conf -z
fi

exec /usr/sbin/squid3 -NYC -d 1 -f /etc/squid3/squid.conf
