#!/bin/bash
set -e

CACHE_MANAGER_EMAIL=${CACHE_MANAGER_EMAIL:-webmaster}
CACHE_MAX_OBJECT_SIZE=${CACHE_MAX_OBJECT_SIZE:-4}
CACHE_MAX_MEM=${CACHE_MAX_MEM:-256}

OVERALL_SPEED_KBPS=${OVERALL_SPEED_KBPS:--1}
if [ ${OVERALL_SPEED_KBPS} -gt 0 ]; then
  OVERALL_SPEED_KBPS=$((${OVERALL_SPEED_KBPS} * 1000  / 8))
fi

INDIVIDUAL_SPEED_KBPS=${INDIVIDUAL_SPEED_KBPS:--1}
if [ ${INDIVIDUAL_SPEED_KBPS} -gt 0 ]; then
  INDIVIDUAL_SPEED_KBPS=$((${INDIVIDUAL_SPEED_KBPS} * 1000  / 8))
fi

# apply squid config
sed 's/{{CACHE_MANAGER_EMAIL}}/'"${CACHE_MANAGER_EMAIL}"'/' -i /etc/squid3/squid.conf
sed 's/{{CACHE_MAX_OBJECT_SIZE}}/'"${CACHE_MAX_OBJECT_SIZE}"'/' -i /etc/squid3/squid.conf
sed 's/{{CACHE_MAX_MEM}}/'"${CACHE_MAX_MEM}"'/' -i /etc/squid3/squid.conf

sed 's/{{INDIVIDUAL_SPEED_KBPS}}/'"${INDIVIDUAL_SPEED_KBPS}"'/g' -i /etc/squid3/squid.conf
sed 's/{{OVERALL_SPEED_KBPS}}/'"${OVERALL_SPEED_KBPS}"'/g' -i /etc/squid3/squid.conf

exec /usr/sbin/squid3 -NYC -d 1 -f /etc/squid3/squid.conf
