apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squid
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - image: sameersbn/squid:4.13-10
        imagePullPolicy: Always
        name: squid
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/spool/squid
          name: cache-volume
        - mountPath: /etc/squid/certs
          name: cert-volume
        - mountPath: /etc/squid/squid.conf
          name: config-volume
          subPath: squid.conf
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: cert-volume
        secret:
          defaultMode: 420
          secretName: squid-cert
      - name: config-volume
        configMap:
          defaultMode: 320
          name: squid-config
